name: Build

on:
  push:
    tags: ["v*.*.*"]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Enable Corepack
        run: corepack enable

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Typecheck
        run: yarn typecheck

  build:
    needs: typecheck
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { engine: chromium }
          - { engine: firefox }
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Enable Corepack
        run: corepack enable

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build:${{matrix.engine}}:prod

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: build-${{matrix.engine}}
          path: dist/${{matrix.engine}}/

  package-source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Create source archive
        run: git ls-files --recurse-submodules | tar caf ./source.tar.gz -T-

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: source
          path: source.tar.gz

  release:
    needs: [build, package-source]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download chromium artifact
        uses: actions/download-artifact@v8
        with:
          name: build-chromium
          path: dist/chromium/

      - name: Download firefox artifact
        uses: actions/download-artifact@v8
        with:
          name: build-firefox
          path: dist/firefox/

      - name: Download source artifact
        uses: actions/download-artifact@v8
        with:
          name: source

      - name: Set the environment variable
        run: echo TAG_WITHOUT_PREFIX=${GITHUB_REF_NAME#v} >> $GITHUB_ENV

      - name: Package Chromium
        run: cd dist/chromium && zip -r ../../42fm_chromium_${{ env.TAG_WITHOUT_PREFIX }}.zip .

      - name: Package Firefox
        run: cd dist/firefox && zip -r ../../42fm_firefox_${{ env.TAG_WITHOUT_PREFIX }}.zip .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            42fm_chromium_${{ env.TAG_WITHOUT_PREFIX }}.zip
            42fm_firefox_${{ env.TAG_WITHOUT_PREFIX }}.zip
            source_${{ env.TAG_WITHOUT_PREFIX }}.tar.gz
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
